-- 코드를 입력하세요
SELECT DISTINCT b.USER_ID, b.NICKNAME, CONCAT(b.CITY," ", b.STREET_ADDRESS1, " ", b.STREET_ADDRESS2) AS 전체주소 ,CONCAT(SUBSTR(TLNO,1,3),'-',SUBSTR(TLNO,4,4),'-',SUBSTR(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD a JOIN USED_GOODS_USER b
ON a.WRITER_ID = b.USER_ID
WHERE  a.WRITER_ID IN (SELECT WRITER_ID
                        FROM USED_GOODS_BOARD
                        GROUP BY WRITER_ID
                        HAVING count(WRITER_ID) >= 3)
ORDER BY b.USER_ID DESC