SELECT a.TITLE AS TITLE, a.BOARD_ID AS BOARD_ID,b.REPLY_ID AS REPLY_ID, b.WRITER_ID AS WRITER_ID, b.CONTENTS AS CONTENTS, date_format(b.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD a JOIN USED_GOODS_REPLY b
ON a.BOARD_ID = b.BOARD_ID and a.CREATED_DATE LIKE '2022-10%'
ORDER BY b.CREATED_DATE, a.TITLE