# 자동차 세단, 10월 대여시작, ID 중복 X, ID 기준 내림차순 정렬

SELECT DISTINCT b.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON a.CAR_ID = b.CAR_ID
WHERE  a.CAR_TYPE LIKE '세단' AND MONTH(b.START_DATE) = 10
ORDER BY a.CAR_ID  DESC;

